### ISSUE TITLE
Single instance continuously failing gRPC connections

### ISSUE THREAD

**Issue by hdub2** [cloudfoundry/log-cache-release#14]
We've observed an issue (once while rolling a cf-d, once when experimenting by changing code on a single instance and rolling it) wherein one instance will fail to answer any requests. During this time, its logs will contain a constant stream of gRPC connection failure messages.

Resolution of this condition requires restarting the *other* instance. This has only been observer to date in a two instance configuration.

**Comment by toddboom** [comment]
Fixed in https://github.com/cloudfoundry/log-cache/commit/3f7228cd5af83dee3bda0008e18e4037d71b25c9

The underlying cause was a deadlock between portions of the meta store.
