### ISSUE TITLE
Invalid expvar-forwarder `maps` default

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/log-cache-release#15]
The default value for the `maps` property in the log-cache-expvar-forwarder job is `nil`:

https://github.com/cloudfoundry/log-cache-release/blob/01b75d50315a0e12548721015d545cdcea0084e2/jobs/log-cache-expvar-forwarder/spec#L54-L67

However, the environment.sh.erb expects a populated value:
https://github.com/cloudfoundry/log-cache-release/blob/01b75d50315a0e12548721015d545cdcea0084e2/jobs/log-cache-expvar-forwarder/templates/environment.sh.erb#L9

It seems bizarre to have a default value that is not accepted.

**Comment by toddboom** [comment]
This was fixed in 6e2a92a14012c601c298416243c3d0f3ccc1eb8c.
