### ISSUE TITLE
Instructions in README to deploy log cache with CF in Bosh lite are out of date

### ISSUE THREAD

**Issue by jtuchscherer** [cloudfoundry/log-cache-release#17]
The code snippet to deploy cf and log cache to bosh lite is not working (wrong paths and file names). Since log cache is now enabled by default in cf deployment, how about just mentioning that and linking to the instructions in the cf-deployment repo.

**Comment by thepeterstone** [comment]
@jtuchscherer we've updated the instructions to work with cf-deployment v3+.

**Comment by jtuchscherer** [comment]
Looks good now. Deployment worked like a charm.
