### ISSUE TITLE
port 8083 has vulnerabilites on doppler VM. 

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/log-cache-release#22]
we have installed CFD 9.5 on our test env. and our scanning is telling us we have vulnerabilities on the log-cache-cf-auth-proxy job which is listening on port 8083.  it is affected by this …

affected by:
https://www.tenable.com/plugins/nessus/20007
https://www.tenable.com/plugins/nessus/42873
tenable.com
SSL Version 2 and 3 Protocol Detection
The remote service encrypts traffic using a protocol with known weaknesses. (Nessus Plugin ID 20007)
tenable.com
SSL Medium Strength Cipher Suites Supported (SWEET32)
The remote service supports the use of medium strength SSL ciphers. (Nessus Plugin ID 42873)

We need a way to specify what TLS protocols are supported and ciphers..
tenable.com
SSL Version 2 and 3 Protocol Detection
The remote service encrypts traffic using a protocol with known weaknesses. (Nessus Plugin ID 20007)
tenable.com
SSL Medium Strength Cipher Suites Supported (SWEET32)
The remote service supports the use of medium strength SSL ciphers. (Nessus Plugin ID 42873)

**Comment by toddboom** [comment]
@andrew-edgar This should be resolved in the most recent versions of log cache. I would recommend upgrading to one of the following:
https://github.com/cloudfoundry/log-cache-release/releases/tag/v2.1.6
https://github.com/cloudfoundry/log-cache-release/releases/tag/v2.2.3
https://github.com/cloudfoundry/log-cache-release/releases/tag/v2.3.1
