### ISSUE TITLE
update log-cache-release to include prometheus 2.12.0

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/log-cache-release#23]
Hi, my team would use log-cache-release and to approve that I've to verify that all its licenses are acceptable.

During my analysis I've found a problematic license in the code of package prometheus, and so I've opened an issue on it: https://github.com/prometheus/prometheus/issues/5783

Its developers have solved the issue in prometheus 2.12.0 (see details in the above issue). 

So, I kindly ask you to update log-cache-release to use the new version of prometheus, 2.12.0. 

Thanks a lot.

**Comment by kitemongerer** [comment]
@luisapace This is completed on the develop branch we just haven't cut a release yet. Here is our story to cut a new release: https://www.pivotaltracker.com/story/show/168840181

**Comment by pianohacker** [comment]
This is fixed as of Log Cache 2.5.2.
