### ISSUE TITLE
Increasing error rate during updates of log-cache

### ISSUE THREAD

**Issue by philippthun** [cloudfoundry/log-cache-release#25]
We are in the process of updating our landscapes from cf-deployment v11.2 to v12.0 and are facing issues with loggregator (more specifically log-cache, updated from v2.3.1 to v2.5.1).

We are used to getting "Stats unavailable" errors sporadically during landscape updates (i.e. re-deployments of doppler VMs), but so far the majority of these temporary downtimes could be handled by retries build into CF CLI (e.g. [here](https://github.com/cloudfoundry/cli/blob/e92078528bf9e62637c253b776533bf919a5dbaa/cf/commands/application/start.go#L359)). During the update from cf-deployment v11.2 to v12.0 the number of "Stats unavailable" errors drastically increased; this led to failing deployments/ updates of applications (cf push) => customer impact!

After these errors showed up in a larger landscape (e.g api VMs: 60, cell VMs: 860, log_api VMs: 15, doppler VMs: 30), we tried to reproduce them in a smaller dev landscape (scaled to 6 log_api VMs and 12 doppler VMs). To detect "Stats unavailable" errors, we queried the "/v2/apps/<app_guid>/stats" endpoint in a loop 10 times per second. In cf-deployment the cloud controller is configured to use log-cache for stats retrieval (see [here](https://github.com/cloudfoundry/cf-deployment/blob/5f5b327ad6d1e9a4d72f1bc9eeea7e7cd20f51d8/cf-deployment.yml#L866)).

As a first test we deployed cf-deployment v11.2 and simply run `bosh -d cf recreate doppler`. This took ~17 minutes and produced *119 to 157 errors* (we ran the test twice), i.e. curling the "/v2/apps/<app_guid>/stats" endpoint failed. When looking into infrastructure logs we saw *~150 'connection refused' log messages* per minute for `syslog_shipper: log-cache`.

The second test was to update cf-deployment from v11.2 to v12.0. Updating the doppler VMs took ~6 minutes (no stemcell update), but we got *281 errors (5 times higher per minute)*. During this time there were *~1600 'connection refused' log messages* per minute for `syslog_shipper: log-cache`.

To check whether these issues were caused by the update itself we run `bosh -d cf recreate doppler` again. This took ~17 minutes (same as before) and produced *660 to 674 errors* (we ran the test twice, 5 times higher). During this time there were *~1900 'connection refused' log messages per minute* for `syslog_shipper: log-cache`.

Did you observe something similar with the new log-cache version? Are there any configuration options we could change in order to improve the situation?

**Comment by philippthun** [comment]
We now think that it might rather be a cloud controller issue: https://cloudfoundry.slack.com/archives/C07C04W4Q/p1571756985051100

**Comment by philippthun** [comment]
After some more tests and investigations, we are back to log-cache...

As the data is sharded across instances, it is not possible to get metrics for an application while the instance storing that specific shard is being updated. Cloud Controller simply talks to another log-cache instance and log-cache v2.3.1 then returned an empty `Logcache::V1::ReadResponse` which was translated into a `stats.usage` section with zero values ("cpu": 0,"mem": 0,"disk": 0) in Cloud Controller's response.

Log-cache v2.5.1 responds with an error instead: `all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp <IP-of-the-VM-storing-the-shard>:8080: connect: connection refused`. This error is then translated into a `Stats unavailable` error by the Cloud Controller and leads to failures during `cf push`, `cf app`, and `cf logs` commands.

**Comment by pusherofbrooms** [comment]
We are seeing what looks like the same issue in our environment. While doppler instances are upgraded, stats attached to the upgrading dopplers can't be gathered. I would go on about the problem but @philippthun has described it better than I can.

**Comment by hev** [comment]
At one point there was a circuit breaker in place to prevent the `Stats unavailable` experience (based on user feedback). We will add this back in.

**Comment by johha** [comment]
We updated log-cache to v2.6.6 and did not see any `Stats unavailable` errors during updating/ `bosh recreate`.
So the circuit breaker is working as expected.

**Comment by pusherofbrooms** [comment]
We're seeing the same goodness in our latest deployment. Closing.

**Comment by heycait** [comment]
This should have been addressed with the v2.6.6 release. Closing this issue.
