### ISSUE TITLE
log-cache job runs out of memory with more than one instance in kubecf

### ISSUE THREAD

**Issue by bikramnehra** [cloudfoundry/log-cache-release#29]
We are running into this issue where upon having two instances of doppler and running [smoke-tests](https://github.com/cloudfoundry/cf-smoke-tests) causes the kube cluster to crash due to out-of-memory issues. We notice `doppler` to be consuming excessive amount of memory until k8s node crashes.

Discussion on CF-Slack: https://cloudfoundry.slack.com/archives/CBFB7NP9B/p1580161281014400

More details including steps to reproduce can be found here:
Original issue: https://github.com/SUSE/kubecf/issues/241

**Comment by bikramnehra** [comment]
We had a preliminary meeting to understand root cause of this problem where it was established that the problem doesn't seem trivial and more metrics is required for debugging. It was theorized that the problem might be somewhere on the juncture of `kubecf` and `log-cache` as a consequence of running in a containerized environment.

@bikramnehra will be checking whether the `smoke-tests` are making use of `cf tail` or `cf logs --recent` in  order to retrieve logs.

@pianohacker will be coming up with a list of metrics data points that would be required to assist with this issue.

**Comment by pianohacker** [comment]
@bikramnehra Metrics that will be useful for debugging:

- `log_cache_ingress` - it would be good to see how much traffic log cache is receiving; it's possible that it's just dramatically underscaled for your throughput.
- `log_cache_memory_utilization` - we saw this percentage greatly underestimate actual usage in the multi-instance scenario. It would be good to know if that's still true for a single instance.
- `log_cache_truncation_duration` - we saw this value rise up to ~10 seconds. Considering that log cache truncates (evicts old envelopes) every 500 ms (see https://github.com/cloudfoundry/log-cache-release/blob/339a718791b9c6cac92d6b3b0680578de15b8af6/src/internal/cache/store/store.go#L77), the fact that one of these truncations is taking 10 seconds indicates that Log Cache is nowhere close to keeping up.

**Comment by bikramnehra** [comment]
Regarding `smoke-tests` using `cf logs --recent` vs `cf tail`:

 The decision is made via [use_log_cache](https://github.com/cloudfoundry/cf-smoke-tests/blob/9a0c2d34a99ca1ee9ebab49dea743a12c7b31ceb/smoke/config.go#L30) property. Since there is no such property defined in the [log-cache-release](https://github.com/cloudfoundry/cf-smoke-tests-release/blob/40.0.123/jobs/smoke_tests/templates/config.json.erb). Therefore `smoke-tests` are likely using `cf logs --recent`.

Also, here are the properties for `smoke-tests` job being set in cf-deployment: https://github.com/cloudfoundry/cf-deployment/blob/v12.18.0/cf-deployment.yml#L277-L290

It seems bit odd though why its left out from the release.

**Comment by MasslessParticle** [comment]
@bikramnehra Historically, that property has determined whether the tests use `cf logs` or `cf tail` to query for logs. It's purely a client-side concern.

https://github.com/cloudfoundry/cf-smoke-tests/blob/05c65862372d5086b0f3b802aedf171d6aa3e17d/smoke/helpers.go#L28-L33

**Comment by pianohacker** [comment]
@bikramnehra Any progress in debugging? Anything we can help with?

**Comment by bikramnehra** [comment]
@pianohacker our priorities shifted due to kubecf release. We will get back to this issue after the release. Thulio is currently looking at a workaround for the time being.

**Comment by mudler** [comment]
I suspect https://github.com/cloudfoundry/gosigar/issues/48 could be related to this issue

**Comment by MasslessParticle** [comment]
We addressed this issue in this release: https://github.com/cloudfoundry/log-cache-release/releases/tag/v2.9.0

We decided that it makes more sense just to set the log-cache memory limit on k8s rather than trying to do anything clever with a container/pod/node's available memory.

Work to scale the cache horizontally will be forthcoming.
