### ISSUE TITLE
log-cache-cf-auth-proxy does not support HS256

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/log-cache-release#31]
Our UAA is setup with a valid HS256 symmetric key configuration.  This works in the rest of CF but the log-cache-cf-auth-proxy fails to decode the keys and fails to authenticate with UAA because of this.

The UAA config using symmetric keys is valid and we are unable to move to asymmetric keys and so the new functionality in CF-CLI 6.50 is broken in our production envs.

We need HS256 supported ASAP as we are being forced to tell our customers they cannot upgrade to cf cli 6.50 and use the new "log-cache" until this is supported traffic controller cannot be deprecated and removed.

**Comment by chendrix** [comment]
We have added a known issue to the 6.50.0 CLI release about this issue

https://github.com/cloudfoundry/cli/releases/tag/v6.50.0

**Comment by pianohacker** [comment]
We have a WIP at https://github.com/cloudfoundry/log-cache-release/tree/hs256 .

**Comment by pianohacker** [comment]
Fixed in https://github.com/cloudfoundry/log-cache-release/commit/b72d60f2639da381ae4ddae0808e6e102bd94888 , will be in the next release.

**Comment by pianohacker** [comment]
Released in https://github.com/cloudfoundry/log-cache-release/releases/tag/v2.7.0 .
