### ISSUE TITLE
cf-auth-proxy slow to authorize when user has access to a large number of apps

### ISSUE THREAD

**Issue by pianohacker** [cloudfoundry/log-cache-release#33]
For users that are not admins (do not have `logs.admin` or `doppler.firehose` scopes in UAA), but have access to a large number of apps (hundreds or thousands), the cf-auth-proxy can take as long as 60 seconds to determine what apps the user has access to.

This information is cached, but due to load balancing, the benefit of that cache for latency purposes is reduced.

**Comment by jaironpm** [comment]
is there an update on this please?

**Comment by pianohacker** [comment]
Fixed in https://github.com/cloudfoundry/log-cache-release/releases/tag/v2.7.0 .
