### ISSUE TITLE
log-cache-nozzle goes to 100% and stops functioning

### ISSUE THREAD

**Issue by pusherofbrooms** [cloudfoundry/log-cache-release#39]
Problem statement:
Since our last upgrade, which changed the log-cache release from v2.6.12 to v2.7.0 (cf-deployment v12.39 to v12.45), in our second largest foundation we've experienced the log-cache-nozzle going to 100% CPU and then failing to function. The only way to restore functionality is to restart log-cache-nozzle. Eventually, all of the log-cache nozzles will go to 100% cpu if I wait long enough.

More detail:
The log-cache-nozzle seems to be silent on logs, so nothing to share there. Below is the set of graphs for CPU from prometheus:
![Screen Shot 2020-06-18 at 6 11 42 AM](https://user-images.githubusercontent.com/7468131/85012104-866c1c00-b130-11ea-810c-f6490c4ac3c2.png)

Reproduction:
I don't know how to reproduce this.

Other details:
This looks similar to https://github.com/cloudfoundry/log-cache/issues/99 but there isn't much detail in that ticket to make a good correlation.

**Comment by Benjamintf1** [comment]
Don't use 2.7.0, use 2.7.1

**Comment by Benjamintf1** [comment]
(I beleive this is likely related to golang 1.14.1

**Comment by pusherofbrooms** [comment]
Ok, this will probably be resolved at our next cf-deployment upgrade then (mid July).

You may need to forgive me for being a little grumpy that there isn't any kind of notification in the release notes saying not to use this version.

**Comment by pianohacker** [comment]
@pusherofbrooms Thanks for the feedback; have added a note to our release notes. Apologies for the delayed notice, we've been getting sporadic information about what releases/environments the Golang 1.14.1 bug affects.

I'm closing this issue for now, but if you run into it in the new release, please let us know.
