### ISSUE TITLE
Protobuf registration conflict when using logcache with protobuf v1.4.x

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/log-cache-release#41]
### What happened
 
When I run the following go program:

```go
package main

import (
    "fmt"
    "net/http"

    logcache "code.cloudfoundry.org/log-cache/pkg/client"
)

func main() {
    client := logcache.NewClient(
        "https://logcache.org",
        logcache.WithHTTPClient(http.DefaultClient),
    )

    fmt.Println("Hello", client)
}
```

I am getting warnings about a protobuf registration conflict as follows:

```
❯ go run main.go
2021/02/09 16:19:36 WARNING: proto: file "egress.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2021/02/09 16:19:36 WARNING: proto: file "ingress.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

Hello &{https://logcache.org  0xdec1c0 <nil> <nil>}

```

Here is my go.mod file

```
module code.cloudfoundry.org/log-cache-repro

go 1.15

require (
    code.cloudfoundry.org/go-loggregator v7.4.0+incompatible // indirect
    code.cloudfoundry.org/log-cache v2.3.1+incompatible
    code.cloudfoundry.org/rfc5424 v0.0.0-20201103192249-000122071b78 // indirect
    github.com/blang/semver v3.5.1+incompatible // indirect
    github.com/golang/protobuf v1.4.3 // indirect
    github.com/grpc-ecosystem/grpc-gateway v1.16.0 // indirect
    github.com/onsi/ginkgo v1.15.0 // indirect
    github.com/onsi/gomega v1.10.5 // indirect
    golang.org/x/net v0.0.0-20210119194325-5f4716e94777 // indirect
    google.golang.org/genproto v0.0.0-20210207032614-bba0dbe2a9ea // indirect
    google.golang.org/grpc v1.35.0 // indirect
)
```

It turns out that this warning is introduced in protobuf v1.4.x introduced this check. Registration seems to be happening twice, once in loggregator and once in logcache:

```
❯ rg egress.proto
vendor/code.cloudfoundry.org/go-loggregator/rpc/loggregator_v2/egress.pb.go
2:// source: egress.proto
789:    Metadata: "egress.proto",
792:func init() { proto.RegisterFile("egress.proto", fileDescriptor_egress_fcae6bb65dce0d2e) }

vendor/code.cloudfoundry.org/log-cache/pkg/rpc/logcache_v1/egress.pb.go
2:// source: egress.proto
437:    Metadata: "egress.proto",
440:func init() { proto.RegisterFile("egress.proto", fileDescriptor_egress_39930eba197832be) }
```

The protobuf docs at https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict point out ways to fix this issue. Maybe log cache should not vendor loggregator or maybe it should not generate the protobuf stubs.

### What was expected to happen:
The program above should not print any warnings

**Comment by kieron-dev** [comment]
Hi. Have you been able to look at this? We're now seeing a panic with the current protobuf v1.5.2

**Comment by Benjamintf1** [comment]
We've handled this by pinning as well. It's...quite unfortunate, and I can't say we've found the time to get into this.

**Comment by denysvitali** [comment]
Any update on the issue? It's not always that easy to pin the protobuf version, especially now that `google.golang.org/protobuf` is used instead

**Comment by mnitchev** [comment]
We have worked around this issue for now by passing `-ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=ignore"` to go build and when running ginkgo as per [this comment in protobuf-go](https://github.com/protocolbuffers/protobuf-go/blob/21e33cc91079beb975323466e237f2486ea29c10/reflect/protoregistry/registry.go#L30-L40). It's not a great solution, but it at least lets us bump our go modules.

**Comment by kieron-dev** [comment]
We have submitted a fix for this in go-log-cache:
* https://github.com/cloudfoundry/go-log-cache/issues/30
* https://github.com/cloudfoundry/go-log-cache/pull/31

It looks like an identical fix would work here.

**Comment by Benjamintf1** [comment]
We think this is done? Feel free to reopen (or @ me) if this isn't the case.
