### ISSUE TITLE
Please create a new release with an updated gosigar module

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry/log-cache-release#43]
There is a new gosigar release https://github.com/cloudfoundry/gosigar/releases/tag/v1.2.0 that should [correctly calculate available memory inside a container](https://github.com/cloudfoundry/gosigar/pull/50), to address #29.

Could you please bump gosigar and make a new log-cache release, so that this can be tested/used by kubecf?

Thank you!

**Comment by Benjamintf1** [comment]
@jandubois why don't you update and vendor and make a pr? I setup pr pipes too.

**Comment by Benjamintf1** [comment]
@jandubois Just to be clear. Release was cut https://github.com/cloudfoundry/log-cache-release/releases/tag/v2.10.3

**Comment by jandubois** [comment]
Thanks for the quick release @Benjamintf1!  I was already notified on Slack 😄
