### ISSUE TITLE
Update the Log Cache API documentation to include the parameters applicable to each endpoint

### ISSUE THREAD

**Issue by anetaivanova-pesheva** [cloudfoundry/log-cache-release#544]
I recently discovered that the `descending=true` parameter can be used when calling the GET /api/v1/read/<sourse_id> endpoint of the Log Cache API, and it correctly orders the results. Here is the request:
```
curl --request GET \
  --url 'https://log-cache.<host>/api/v1/read/<id>?descending=true&envelope_types=LOG&limit=1000' \
  --header 'Authorization: <Bearer token> \
  --header 'Content-Type: application/json' 

```
I noticed that parameter `descending` is not described in the [README.md](https://github.com/cloudfoundry/log-cache-release/blob/main/src/README.md) . Could you please update the documentation with information about this and any other parameters that may not be described? I believe this would be very helpful for users of the API.

**Comment by chombium** [comment]
Hi @anetaivanova-pesheva,

thanks for opening the issue. I guess we should review the API docs. I you want, feel free to add the parameter in the readme.
